creation_rules:
  - path_regex: iac\.yml$
    age: age16hthywte685jmwww0y694f7cy9pzded7aagly7f287s9444zhsms6tpq9x,age1xrpyhjedhc262qz6dgtek36fu2gd0tdgrsv8xvvf4xu9mrj4cghs4ujedq,age1lk9l3hucfatw8muugllx82h0pvjlrapa0yyes353gqp390xs4prqzlnqjk
    unencrypted_regex: "^(image_name|app_domains)$"
  - path_regex: \.env$
    age: age16hthywte685jmwww0y694f7cy9pzded7aagly7f287s9444zhsms6tpq9x,age1xrpyhjedhc262qz6dgtek36fu2gd0tdgrsv8xvvf4xu9mrj4cghs4ujedq,age1lk9l3hucfatw8muugllx82h0pvjlrapa0yyes353gqp390xs4prqzlnqjk
