services:
  app:
    environment:
      PUBLIC_SIMPLE_ANALYTICS_DOMAIN: tientjeketama.nl
    networks:
      - default
      - traefik
    restart: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.http.routers.app.priority: "1"
      traefik.http.routers.app.rule: "Host(`dev.tientjeketama.nl`) || Host(`prod.tientjeketama.nl`)"
      traefik.http.routers.app.entrypoints: "websecure"
      traefik.http.routers.app.tls.certresolver: "letsencrypt"
      traefik.http.routers.app.middlewares: "app-headers@file,app-buffering@file,app-permissions@docker"
      traefik.http.services.app.loadbalancer.server.port: "3000"
      traefik.http.middlewares.app-permissions.headers.customResponseHeaders.Permissions-Policy: "accelerometer=(), autoplay=(self), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()"
  db:
    restart: unless-stopped

networks:
  traefik:
    external: true
