on:
  push:
    branches: [main]

jobs:
  build-and-push:
    uses: rednaw/iac/.github/workflows/_build-and-push.yml@main
    secrets:
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
